# Generated by Django 5.1.1 on 2024-10-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_bookingcars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingcars',
            options={'ordering': ['-booked_at'], 'verbose_name_plural': 'Booking Cars'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='status',
            field=models.CharField(choices=[('Yes', 'Booked'), ('No', 'Available')], default='No', max_length=50),
        ),
    ]
