# Generated by Django 5.1.1 on 2024-11-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile'),
        ('cars', '0005_delete_carsbookingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcars',
            name='profile_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
    ]
